### ISSUE TITLE
llama-stack-client-swift

### ISSUE THREAD

**Issue by nashahgit** [meta-llama/llama-stack-client-swift#10]
Getting error while build after installing the llama-stack-client-swift package in Xcode. 
`Value of type 'Operations.post_sol_agents_sol_turn_sol_create.Output.Ok.Body' has no member 'text_event_hyphen_stream'`

File remoteAgents in LlamaStackClient

![Uploading Screenshot 2024-10-29 at 7.31.27 PM.png…]()

**Comment by alelordelo** [comment]
+1

**Comment by yauheni-rahouski** [comment]
+1

**Comment by dltn** [comment]
This should be fixed after https://github.com/meta-llama/llama-stack-client-swift/commit/9586d1accebc87dfd63bf25a6509ebec4b044f9a – please re-open if you're still experiencing this
